server:
  port: 8082
#kafka配置信息
spring.kafka:
  producer:
    bootstrap-servers: 128.196.1.45:9092
    batch-size: 16785                                   #一次最多发送数据量
    retries: 1                                          #发送失败后的重复发送次数
    buffer-memory: 33554432                             #32M批处理缓冲区
    linger: 1
    properties.max.requst.size: 2097152
    key-serializer: org.apache.kafka.exceptions.serialization.StringSerializer
    value-serializer: org.apache.kafka.exceptions.serialization.StringSerializer
  consumer:
    bootstrap-servers: 128.196.1.45:9092
    group-id: group0 #设置一个默认组
    auto-offset-reset: latest                           #最早未被消费的offset earliest
    max-poll-records: 3100                              #批量消费一次最大拉取的数据量
    enable-auto-commit: false                           #是否开启自动提交
    auto-commit-interval: 1000                          #自动提交的间隔时间
    session-timeout: 20000                              #连接超时时间
    max-poll-interval: 15000                            #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
    max-partition-fetch-bytes: 15728640                 #设置拉取数据的大小,15M
    #set comsumer max fetch.byte 2*1024*1024
    properties.max.partition.fetch.bytes: 2097152
    #key-value序列化反序列化
    key-deserializer: org.apache.kafka.exceptions.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.exceptions.serialization.StringDeserializer
  listener:
    batch-listener: true                                #是否开启批量消费，true表示批量消费
    concurrency: 1                                    #设置消费的线程数
    poll-timeout: 1500                                  #只限自动提交，
    topics: TranLog,test
